Started by user [8mha:////4C8zTO/v0UlG+vQ5Fjm5jTf9kR93yL5yxTMP2X04T9v8AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgYu/dLi1CL9ovz8EgDKVWzSvwAAAA==[0mroot
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4GiJsi7Mya/6bg7lYfwMQTzNVpzT54TxwGFsrEp/EcRtAAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQi/eTKAkMD3aLUXKBKfQCdwg2/zAAAAA==[0mcyp10-remote in /root/.jenkins/workspace/test-nic@2
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (set args)
[8mha:////4KpTcsSlLG7yEvo1vGv2QG1z86HMYkLASFXVuKwhd7SZAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaWGsbAmNJ0AWEZb8zwLrbuWJvJp3kLiJlZNMMm+a93rDOic4UbLcG+wdZu14DKOti0+U+lugiXu6ck2YKRguzSSpM+cFJRUDS1gDKwEbgzpQdmgLbIVXD9UGhba9lFS/o4DGdQM8gYlqLiqVL8wJdvexy4Q/z18BzLEA29ce4gfg7KmOvAAAAA==[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-nic/npxtester/conf/change_args.py '{"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/","vm_image_conf":{"image1":"ubuntu20.04.img","image2":"ubuntu20.04_2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.112.97.157","connect_switch_sut_pf":"ens787f0","pf1":"ens787f0","pf1_ipv6":"fe80::b696:91ff:fe9c:f760","os":"rehat"},"dhcp":{"ipv4":"192.168.10.10","ipv6":"fe80::b696:91ff:fe9c:f762"}}'
[8mha:////4ChDQWb8Lvr0RoXQ1L8EY4p37+Po0Q8Mb8bchs8JeqDJAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbGRNjZUtoPAGyiLDkfxZYdytP5NW8g8RNrJxkknnTvNcb1jnBiZLl3mDvMGvHYxhtXXyi1N8CTdzTlWvCTMFwaSZJnTkvKKkYWMIaWAnYGNSBskNbYCu8eqg2KLTtpaT6HQU0rhvgCUxUc1GpfGFOsLuPXSb8ef4KYI6xADvU7j9Dg2gqvAAAAA==[0m[Pipeline] }
[8mha:////4J0p4zt/+On27QitkvU5TFB8M2wwWYWaAHIuYiUer4fkAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQRbWRhjZUtoPAGyiLDkfxZYdytP5NW8g8RNrJxkknnTvNcb1jnBiZLl3mDvMGvHYxhtXXyi1N8CTdzTlWvCTMFwaSZJnTkvKKkYWMIaWAnYGNSBskNbYCu8eqg2KLTtpaT6HQU0rhvgCUxUc1GpfGFOsLuPXSb8ef4KYI6xADvU7j9J+wGOvAAAAA==[0m[Pipeline] // stage
[8mha:////4Ea3/4ZYuTM98yMZ9UntzMXOyQ2ItSOm6XAUUO4QqkITAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQDEh2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INtuQqUcEAAAA=[0m[Pipeline] stage
[8mha:////4IJd0qxfNFkcgwUT9OFke9rxaJjwCH2G9mHJ+5FMmbLfAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycoiUzoiJNerCCUITQtLo/zZJSSdOxNW4Ay2VmPBg2Zas93pDGQOcKBjuNHYWY2t570czJ54pdDdPmTu68pYwkte80bkhpc9rbShpWFUw2AjYamw9RYsmwU44+ZCVl2iqSwrzdhTArBrgCYWYyUmG9C1TgP19VJHwx/kLgKlPwOrDYvXyLD8BobDcwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4KACpsxoNqug+yeGIE2K55MD+IyPDLfbYOrean7h1Zl/AAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggysXWsbBkaT4AJIoT5nwCRVJ7Iq3kH0cxYucXOvm3e8wXrGOBIQTOrcDAYO8O8m3RZLFMYro4ys3RhHWEkp5hQWVCvTgsKSgqWVDWsOGwUdo6iQZ1gy628y8ZJ1M05hfIdONSmH+EBFS/mJEP6whxgd5v6SPjz/BXA7BPUbfupvX8DpQJrNb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-nic/npxtester/Tests/testNics/nic_main.py
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/test-nic/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 8 items / 3 deselected / 5 selected

../test-nic/npxtester/Tests/testNics/test_network_sriov_stress.py 2021-11-26 13:58:14 - NicTestFixture.py - [line:28] - root - INFO - Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[ubuntu20.04_2.img-ubuntu20.04.img]
2021-11-26 13:58:14 - NicTestFixture.py - [line:29] - root - INFO - setup log for testing in the fixture class fbefore
2021-11-26 13:58:14 - test_network_sriov_stress.py - [line:30] - root - INFO - SSH SUT and setup configurations in the setup function.
2021-11-26 13:58:14 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2021-11-26 13:58:14 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (publickey) failed.
2021-11-26 13:58:14 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2021-11-26 13:58:14 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.157
2021-11-26 13:58:14 - test_network_sriov_stress.py - [line:349] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2021-11-26 13:58:17 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens787f0 | awk '{print $1;}'
2021-11-26 13:58:18 - sshInstance.py - [line:48] - root - INFO - 0000:31:00.0
0000:31:01.0
0000:31:01.1
0000:31:01.2
0000:31:01.3

2021-11-26 13:58:23 - test_network_sriov_stress.py - [line:80] - root - INFO - pf_id was found: 0000:31:00.0
0000:31:01.0
0000:31:01.1
0000:31:01.2
0000:31:01.3

2021-11-26 13:58:23 - test_network_sriov_stress.py - [line:357] - root - INFO - format_pf_id is 0000\:31\:00.0
0000:31:01.0
0000:31:01.1
0000:31:01.2
0000:31:01.3

2021-11-26 13:58:23 - test_network_sriov_stress.py - [line:360] - root - INFO - pf_id_key: 31
2021-11-26 13:58:28 - sshInstance.py - [line:89] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Nov 26 13:53:40 2021 from 10.238.10.192
[root@WW30CYP10 ~]# ifconfig ens787f0 192.168.10.11
[root@WW30CYP10 ~]# 
2021-11-26 13:58:31 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens787f0
2021-11-26 13:58:34 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens787f0/device/sriov_numvfs
2021-11-26 13:58:34 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 13:58:39 - test_network_sriov_stress.py - [line:95] - root - INFO - Successfully Virtualized PF to VFs.
2021-11-26 13:58:42 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2021-11-26 13:58:42 - sshInstance.py - [line:48] - root - INFO - 31:01.0
31:01.1
31:01.2
31:01.3

2021-11-26 13:58:47 - test_network_sriov_stress.py - [line:109] - root - INFO - Succssfully Gotten vf_id list:

2021-11-26 13:58:50 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2021-11-26 13:58:50 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2021-11-26 13:58:55 - test_network_sriov_stress.py - [line:162] - root - INFO - Successfuly modeprobe vfio-pci
2021-11-26 13:58:58 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 31:01.0
2021-11-26 13:58:59 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 13:59:04 - test_network_sriov_stress.py - [line:141] - root - INFO - Successfuly bound VF to vfio-pci
2021-11-26 13:59:07 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 31:01.1
2021-11-26 13:59:07 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 13:59:12 - test_network_sriov_stress.py - [line:141] - root - INFO - Successfuly bound VF to vfio-pci
2021-11-26 13:59:12 - test_network_sriov_stress.py - [line:381] - root - INFO - lspci -Dnn | grep 31:01.1
2021-11-26 13:59:15 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 31:01.1
2021-11-26 13:59:16 - sshInstance.py - [line:48] - root - INFO - 0000:31:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2021-11-26 13:59:21 - test_network_sriov_stress.py - [line:392] - root - INFO - Successfully get vf device id: 8086:1889
2021-11-26 13:59:24 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2021-11-26 13:59:24 - sshInstance.py - [line:48] - root - INFO - yes

2021-11-26 13:59:29 - test_network_sriov_stress.py - [line:170] - root - INFO - Default network is active? yes

2021-11-26 13:59:33 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:226553): [1;33mWARNING[0m **: [34m13:59:42.411[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2021-11-26 13:59:36 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW30CYP10 ~]# 
2021-11-26 13:59:39 - test_network_sriov_stress.py - [line:205] - root - INFO - Successfully created a VM: VMtest1
2021-11-26 13:59:43 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:226627): [1;33mWARNING[0m **: [34m13:59:52.352[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2021-11-26 13:59:46 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW30CYP10 ~]# 
2021-11-26 13:59:49 - test_network_sriov_stress.py - [line:205] - root - INFO - Successfully created a VM: VMtest2
2021-11-26 13:59:52 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2021-11-26 13:59:52 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 13:59:57 - test_network_sriov_stress.py - [line:221] - root - ERROR - not found IP of VMtest1
2021-11-26 14:01:00 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:01:00 - sshInstance.py - [line:48] - root - INFO - 192.168.122.51/24

2021-11-26 14:01:05 - test_network_sriov_stress.py - [line:216] - root - INFO - Successfully got VMtest1 IP: 192.168.122.51/24

2021-11-26 14:01:08 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:01:08 - sshInstance.py - [line:48] - root - INFO - 192.168.122.153/24

2021-11-26 14:01:13 - test_network_sriov_stress.py - [line:216] - root - INFO - Successfully got VMtest2 IP: 192.168.122.153/24

2021-11-26 14:01:13 - test_network_sriov_stress.py - [line:409] - root - INFO - ip of VM1: 192.168.122.51
2021-11-26 14:01:13 - test_network_sriov_stress.py - [line:410] - root - INFO - ip of VM1: 192.168.122.153
2021-11-26 14:01:17 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.51
PING 192.168.122.51 (192.168.122.51) 56(84) bytes of data.
64 bytes from 192.168.122.51: icmp_seq=1 ttl=64 time=0.130 ms
2021-11-26 14:01:18 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=2 ttl=64 time=0.095 ms
2021-11-26 14:01:19 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=3 ttl=64 time=0.085 ms
2021-11-26 14:01:20 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=4 ttl=64 time=0.089 ms
2021-11-26 14:01:21 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=5 ttl=64 time=0.092 ms

--- 192.168.122.51 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4085ms
rtt min/avg/max/mdev = 0.085/0.098/0.130/0.017 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:01:29 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.51
The authenticity of host '192.168.122.51 (192.168.122.51)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2021-11-26 14:01:37 - sshInstance.py - [line:89] - root - INFO - yes
Warning: Permanently added '192.168.122.51' (ECDSA) to the list of known hosts.
root@192.168.122.51's password: 
2021-11-26 14:01:45 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:01:51 AM EST
  System load:  0.46               Processes:             140
  Usage of /:   47.5% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.51
  Swap usage:   0%

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Thu Nov 25 22:28:09 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:01:53 - sshInstance.py - [line:89] - root - INFO - lspci -Dnn | grep "8086:1889" | awk '{print $1;}'
0000:00:05.0
root@localhost:~# 
2021-11-26 14:01:59 - test_network_sriov_stress.py - [line:306] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2021-11-26 14:02:04 - sshInstance.py - [line:89] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2021-11-26 14:02:09 - test_network_sriov_stress.py - [line:317] - root - INFO - Successfully got vf device name of vm1: ens5
2021-11-26 14:02:14 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2021-11-26 14:02:17 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens5
2021-11-26 14:02:22 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2021-11-26 14:02:30 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2021-11-26 14:02:38 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2021-11-26 14:02:46 - sshInstance.py - [line:89] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2021-11-26 14:02:54 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2021-11-26 14:03:02 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.51 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:03:09 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.153
PING 192.168.122.153 (192.168.122.153) 56(84) bytes of data.
64 bytes from 192.168.122.153: icmp_seq=1 ttl=64 time=0.132 ms
2021-11-26 14:03:10 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=2 ttl=64 time=0.073 ms
2021-11-26 14:03:11 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=3 ttl=64 time=0.104 ms
2021-11-26 14:03:12 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=4 ttl=64 time=0.081 ms
2021-11-26 14:03:13 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=5 ttl=64 time=0.068 ms

--- 192.168.122.153 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4086ms
rtt min/avg/max/mdev = 0.068/0.091/0.132/0.025 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:03:21 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.153
The authenticity of host '192.168.122.153 (192.168.122.153)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2021-11-26 14:03:29 - sshInstance.py - [line:89] - root - INFO - yes
Warning: Permanently added '192.168.122.153' (ECDSA) to the list of known hosts.
root@192.168.122.153's password: 
2021-11-26 14:03:37 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:03:43 AM EST
  System load:  0.01               Processes:             149
  Usage of /:   47.9% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.153
  Swap usage:   0%

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Thu Nov 25 22:29:53 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:03:45 - sshInstance.py - [line:89] - root - INFO - lspci -Dnn | grep "8086:1889" | awk '{print $1;}'
0000:00:05.0
root@localhost:~# 
2021-11-26 14:03:51 - test_network_sriov_stress.py - [line:306] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2021-11-26 14:03:56 - sshInstance.py - [line:89] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2021-11-26 14:04:01 - test_network_sriov_stress.py - [line:317] - root - INFO - Successfully got vf device name of vm1: ens5
2021-11-26 14:04:06 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2021-11-26 14:04:09 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens5
2021-11-26 14:04:14 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2021-11-26 14:04:22 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2021-11-26 14:04:30 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2021-11-26 14:04:38 - sshInstance.py - [line:89] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2021-11-26 14:04:46 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 692 (692.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 8  bytes 696 (696.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2021-11-26 14:04:54 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.153 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:04:57 - test_network_sriov_stress.py - [line:428] - root - INFO - Ping two vms IP from SUT:
2021-11-26 14:05:01 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=4.74 ms
2021-11-26 14:05:02 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.068 ms
2021-11-26 14:05:03 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.035 ms
2021-11-26 14:05:04 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.045 ms
2021-11-26 14:05:05 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.059 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4089ms
rtt min/avg/max/mdev = 0.035/0.989/4.741/1.876 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:05:12 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.030 ms
2021-11-26 14:05:13 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.010 ms
2021-11-26 14:05:14 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.009 ms
2021-11-26 14:05:15 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.018 ms
2021-11-26 14:05:16 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.008 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4084ms
rtt min/avg/max/mdev = 0.008/0.015/0.030/0.008 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:05:19 - test_network_sriov_stress.py - [line:436] - root - INFO - ping VMtest2 IP from VMtest1
2021-11-26 14:05:24 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.51
PING 192.168.122.51 (192.168.122.51) 56(84) bytes of data.
64 bytes from 192.168.122.51: icmp_seq=1 ttl=64 time=0.143 ms
2021-11-26 14:05:25 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=2 ttl=64 time=0.091 ms
2021-11-26 14:05:26 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=3 ttl=64 time=0.197 ms
2021-11-26 14:05:27 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=4 ttl=64 time=0.084 ms
2021-11-26 14:05:28 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=5 ttl=64 time=0.091 ms

--- 192.168.122.51 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4079ms
rtt min/avg/max/mdev = 0.084/0.121/0.197/0.043 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:05:36 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.51
root@192.168.122.51's password: 
2021-11-26 14:05:44 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:05:50 AM EST
  System load:  0.01               Processes:             129
  Usage of /:   47.5% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.51
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:01:52 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:05:51 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.147 ms
2021-11-26 14:05:52 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.040 ms
2021-11-26 14:05:53 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.035 ms
2021-11-26 14:05:54 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.038 ms
2021-11-26 14:05:55 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.040 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4075ms
rtt min/avg/max/mdev = 0.035/0.060/0.147/0.043 ms
root@localhost:~# 
2021-11-26 14:06:34 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.51 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:06:37 - test_network_sriov_stress.py - [line:444] - root - INFO - ping VMtest2 IP from VMtest1
2021-11-26 14:06:41 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.11 192.168.10.10
PING 192.168.10.10 (192.168.10.10) from 192.168.10.11 : 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.034 ms
2021-11-26 14:06:42 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.011 ms
2021-11-26 14:06:43 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.011 ms
2021-11-26 14:06:44 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.018 ms
2021-11-26 14:06:45 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.012 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4112ms
rtt min/avg/max/mdev = 0.011/0.017/0.034/0.009 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:06:51 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens787f0/device/sriov_numvfs
2021-11-26 14:06:53 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:06:58 - test_network_sriov_stress.py - [line:237] - root - INFO - Successfully removed VFs from PF.
2021-11-26 14:07:01 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2021-11-26 14:07:02 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2021-11-26 14:07:07 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully shut down the VM: VMtest1
2021-11-26 14:07:10 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2021-11-26 14:07:10 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2021-11-26 14:07:15 - test_network_sriov_stress.py - [line:254] - root - INFO - Successfully removed the VM: VMtest1
2021-11-26 14:07:18 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2021-11-26 14:07:18 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2021-11-26 14:07:23 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully shut down the VM: VMtest2
2021-11-26 14:07:26 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2021-11-26 14:07:26 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2021-11-26 14:07:31 - test_network_sriov_stress.py - [line:254] - root - INFO - Successfully removed the VM: VMtest2
2021-11-26 14:07:31 - test_network_sriov_stress.py - [line:349] - root - INFO - 

********************************************************Stress Disable and Enable for 2 time when VF is Assigned VM guest.*************************************************************


2021-11-26 14:07:34 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens787f0 | awk '{print $1;}'
2021-11-26 14:07:35 - sshInstance.py - [line:48] - root - INFO - 0000:31:00.0

2021-11-26 14:07:40 - test_network_sriov_stress.py - [line:80] - root - INFO - pf_id was found: 0000:31:00.0

2021-11-26 14:07:40 - test_network_sriov_stress.py - [line:357] - root - INFO - format_pf_id is 0000\:31\:00.0

2021-11-26 14:07:40 - test_network_sriov_stress.py - [line:360] - root - INFO - pf_id_key: 31
2021-11-26 14:07:45 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 192.168.10.11
[root@WW30CYP10 ~]# 
2021-11-26 14:07:48 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens787f0
2021-11-26 14:07:51 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens787f0/device/sriov_numvfs
2021-11-26 14:07:51 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:07:56 - test_network_sriov_stress.py - [line:95] - root - INFO - Successfully Virtualized PF to VFs.
2021-11-26 14:07:59 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2021-11-26 14:07:59 - sshInstance.py - [line:48] - root - INFO - 31:01.0
31:01.1
31:01.2
31:01.3

2021-11-26 14:08:04 - test_network_sriov_stress.py - [line:109] - root - INFO - Succssfully Gotten vf_id list:

2021-11-26 14:08:07 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2021-11-26 14:08:07 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2021-11-26 14:08:12 - test_network_sriov_stress.py - [line:162] - root - INFO - Successfuly modeprobe vfio-pci
2021-11-26 14:08:15 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 31:01.0
2021-11-26 14:08:16 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:08:21 - test_network_sriov_stress.py - [line:141] - root - INFO - Successfuly bound VF to vfio-pci
2021-11-26 14:08:24 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 31:01.1
2021-11-26 14:08:25 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:08:30 - test_network_sriov_stress.py - [line:141] - root - INFO - Successfuly bound VF to vfio-pci
2021-11-26 14:08:30 - test_network_sriov_stress.py - [line:381] - root - INFO - lspci -Dnn | grep 31:01.1
2021-11-26 14:08:33 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 31:01.1
2021-11-26 14:08:33 - sshInstance.py - [line:48] - root - INFO - 0000:31:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2021-11-26 14:08:38 - test_network_sriov_stress.py - [line:392] - root - INFO - Successfully get vf device id: 8086:1889
2021-11-26 14:08:41 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2021-11-26 14:08:41 - sshInstance.py - [line:48] - root - INFO - yes

2021-11-26 14:08:46 - test_network_sriov_stress.py - [line:170] - root - INFO - Default network is active? yes

2021-11-26 14:08:50 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:227889): [1;33mWARNING[0m **: [34m14:08:59.525[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:08:53 - test_network_sriov_stress.py - [line:202] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:227889): [1;33mWARNING[0m **: [34m14:08:59.525[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:08:53 - test_network_sriov_stress.py - [line:203] - root - ERROR - Failed to create a VM: 
2021-11-26 14:08:57 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:227957): [1;33mWARNING[0m **: [34m14:09:06.540[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2021-11-26 14:09:00 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW30CYP10 ~]# 
2021-11-26 14:09:03 - test_network_sriov_stress.py - [line:205] - root - INFO - Successfully created a VM: VMtest1
2021-11-26 14:09:07 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:228022): [1;33mWARNING[0m **: [34m14:09:16.544[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:09:10 - test_network_sriov_stress.py - [line:202] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:228022): [1;33mWARNING[0m **: [34m14:09:16.544[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:09:10 - test_network_sriov_stress.py - [line:203] - root - ERROR - Failed to create a VM: 
2021-11-26 14:09:14 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:228081): [1;33mWARNING[0m **: [34m14:09:23.533[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2021-11-26 14:09:17 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW30CYP10 ~]# 
2021-11-26 14:09:20 - test_network_sriov_stress.py - [line:205] - root - INFO - Successfully created a VM: VMtest2
2021-11-26 14:09:23 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:09:23 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:09:28 - test_network_sriov_stress.py - [line:221] - root - ERROR - not found IP of VMtest1
2021-11-26 14:10:31 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:10:31 - sshInstance.py - [line:48] - root - INFO - 192.168.122.51/24

2021-11-26 14:10:36 - test_network_sriov_stress.py - [line:216] - root - INFO - Successfully got VMtest1 IP: 192.168.122.51/24

2021-11-26 14:10:39 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:10:39 - sshInstance.py - [line:48] - root - INFO - 192.168.122.153/24

2021-11-26 14:10:44 - test_network_sriov_stress.py - [line:216] - root - INFO - Successfully got VMtest2 IP: 192.168.122.153/24

2021-11-26 14:10:44 - test_network_sriov_stress.py - [line:409] - root - INFO - ip of VM1: 192.168.122.51
2021-11-26 14:10:44 - test_network_sriov_stress.py - [line:410] - root - INFO - ip of VM1: 192.168.122.153
2021-11-26 14:10:48 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.51
PING 192.168.122.51 (192.168.122.51) 56(84) bytes of data.
64 bytes from 192.168.122.51: icmp_seq=1 ttl=64 time=0.268 ms
2021-11-26 14:10:49 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=2 ttl=64 time=0.081 ms
2021-11-26 14:10:50 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=3 ttl=64 time=0.163 ms
2021-11-26 14:10:51 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=4 ttl=64 time=0.073 ms
2021-11-26 14:10:52 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=5 ttl=64 time=0.119 ms

--- 192.168.122.51 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4076ms
rtt min/avg/max/mdev = 0.073/0.140/0.268/0.072 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:11:00 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.51
root@192.168.122.51's password: 
2021-11-26 14:11:08 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:11:16 AM EST
  System load:  0.24               Processes:             139
  Usage of /:   47.5% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.51
  Swap usage:   0%

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:05:50 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:11:16 - sshInstance.py - [line:89] - root - INFO - lspci -Dnn | grep "8086:1889" | awk '{print $1;}'
0000:00:05.0
root@localhost:~# 
2021-11-26 14:11:22 - test_network_sriov_stress.py - [line:306] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2021-11-26 14:11:27 - sshInstance.py - [line:89] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2021-11-26 14:11:32 - test_network_sriov_stress.py - [line:317] - root - INFO - Successfully got vf device name of vm1: ens5
2021-11-26 14:11:37 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2021-11-26 14:11:41 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens5
2021-11-26 14:11:46 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2021-11-26 14:11:54 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2021-11-26 14:12:02 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2021-11-26 14:12:10 - sshInstance.py - [line:89] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2021-11-26 14:12:18 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 692 (692.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2021-11-26 14:12:26 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.51 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:12:33 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.153
PING 192.168.122.153 (192.168.122.153) 56(84) bytes of data.
64 bytes from 192.168.122.153: icmp_seq=1 ttl=64 time=0.299 ms
2021-11-26 14:12:34 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=2 ttl=64 time=0.102 ms
2021-11-26 14:12:35 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=3 ttl=64 time=0.157 ms
2021-11-26 14:12:36 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=4 ttl=64 time=0.140 ms
2021-11-26 14:12:37 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=5 ttl=64 time=0.110 ms

--- 192.168.122.153 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4087ms
rtt min/avg/max/mdev = 0.102/0.161/0.299/0.072 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:12:45 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.153
root@192.168.122.153's password: 
2021-11-26 14:12:53 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:13:00 AM EST
  System load:  0.06               Processes:             136
  Usage of /:   47.9% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.153
  Swap usage:   0%

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:03:44 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:13:01 - sshInstance.py - [line:89] - root - INFO - lspci -Dnn | grep "8086:1889" | awk '{print $1;}'
0000:00:05.0
root@localhost:~# 
2021-11-26 14:13:07 - test_network_sriov_stress.py - [line:306] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2021-11-26 14:13:12 - sshInstance.py - [line:89] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2021-11-26 14:13:17 - test_network_sriov_stress.py - [line:317] - root - INFO - Successfully got vf device name of vm1: ens5
2021-11-26 14:13:22 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2021-11-26 14:13:25 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens5
2021-11-26 14:13:30 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2021-11-26 14:13:38 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2021-11-26 14:13:46 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2021-11-26 14:13:54 - sshInstance.py - [line:89] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2021-11-26 14:14:02 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 1026 (1.0 KB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 8  bytes 696 (696.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2021-11-26 14:14:10 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.153 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:14:13 - test_network_sriov_stress.py - [line:428] - root - INFO - Ping two vms IP from SUT:
2021-11-26 14:14:17 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.164 ms
2021-11-26 14:14:18 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.051 ms
2021-11-26 14:14:19 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.058 ms
2021-11-26 14:14:20 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.110 ms
2021-11-26 14:14:21 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.041 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4098ms
rtt min/avg/max/mdev = 0.041/0.084/0.164/0.047 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:14:28 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.123 ms
2021-11-26 14:14:29 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.038 ms
2021-11-26 14:14:30 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.036 ms
2021-11-26 14:14:31 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.032 ms
2021-11-26 14:14:32 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.030 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4092ms
rtt min/avg/max/mdev = 0.030/0.051/0.123/0.036 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:14:35 - test_network_sriov_stress.py - [line:436] - root - INFO - ping VMtest2 IP from VMtest1
2021-11-26 14:14:39 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.51
PING 192.168.122.51 (192.168.122.51) 56(84) bytes of data.
64 bytes from 192.168.122.51: icmp_seq=1 ttl=64 time=0.131 ms
2021-11-26 14:14:40 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=2 ttl=64 time=0.081 ms
2021-11-26 14:14:41 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=3 ttl=64 time=0.093 ms
2021-11-26 14:14:42 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=4 ttl=64 time=0.092 ms
2021-11-26 14:14:43 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=5 ttl=64 time=0.092 ms

--- 192.168.122.51 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4087ms
rtt min/avg/max/mdev = 0.081/0.097/0.131/0.021 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:14:51 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.51
root@192.168.122.51's password: 
2021-11-26 14:14:59 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:15:06 AM EST
  System load:  0.16               Processes:             133
  Usage of /:   47.5% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.51
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:11:16 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:15:06 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=4.78 ms
2021-11-26 14:15:07 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.072 ms
2021-11-26 14:15:08 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.039 ms
2021-11-26 14:15:09 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.040 ms
2021-11-26 14:15:10 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.045 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4071ms
rtt min/avg/max/mdev = 0.039/0.995/4.783/1.893 ms
root@localhost:~# 
2021-11-26 14:15:49 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.51 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:15:52 - test_network_sriov_stress.py - [line:444] - root - INFO - ping VMtest2 IP from VMtest1
2021-11-26 14:15:56 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.11 192.168.10.10
PING 192.168.10.10 (192.168.10.10) from 192.168.10.11 : 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.032 ms
2021-11-26 14:15:57 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.011 ms
2021-11-26 14:15:58 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.016 ms
2021-11-26 14:15:59 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.009 ms
2021-11-26 14:16:00 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.010 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4122ms
rtt min/avg/max/mdev = 0.009/0.015/0.032/0.009 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:16:06 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens787f0/device/sriov_numvfs
2021-11-26 14:16:08 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:16:13 - test_network_sriov_stress.py - [line:237] - root - INFO - Successfully removed VFs from PF.
2021-11-26 14:16:16 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2021-11-26 14:16:17 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2021-11-26 14:16:22 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully shut down the VM: VMtest1
2021-11-26 14:16:25 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2021-11-26 14:16:25 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2021-11-26 14:16:30 - test_network_sriov_stress.py - [line:254] - root - INFO - Successfully removed the VM: VMtest1
2021-11-26 14:16:33 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2021-11-26 14:16:33 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2021-11-26 14:16:38 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully shut down the VM: VMtest2
2021-11-26 14:16:41 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2021-11-26 14:16:41 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2021-11-26 14:16:46 - test_network_sriov_stress.py - [line:254] - root - INFO - Successfully removed the VM: VMtest2
2021-11-26 14:16:46 - test_network_sriov_stress.py - [line:349] - root - INFO - 

********************************************************Stress Disable and Enable for 3 time when VF is Assigned VM guest.*************************************************************


2021-11-26 14:16:49 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens787f0 | awk '{print $1;}'
2021-11-26 14:16:50 - sshInstance.py - [line:48] - root - INFO - 0000:31:00.0

2021-11-26 14:16:55 - test_network_sriov_stress.py - [line:80] - root - INFO - pf_id was found: 0000:31:00.0

2021-11-26 14:16:55 - test_network_sriov_stress.py - [line:357] - root - INFO - format_pf_id is 0000\:31\:00.0

2021-11-26 14:16:55 - test_network_sriov_stress.py - [line:360] - root - INFO - pf_id_key: 31
2021-11-26 14:17:00 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 192.168.10.11
[root@WW30CYP10 ~]# 
2021-11-26 14:17:03 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens787f0
2021-11-26 14:17:06 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens787f0/device/sriov_numvfs
2021-11-26 14:17:06 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:17:11 - test_network_sriov_stress.py - [line:95] - root - INFO - Successfully Virtualized PF to VFs.
2021-11-26 14:17:14 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2021-11-26 14:17:14 - sshInstance.py - [line:48] - root - INFO - 31:01.0
31:01.1
31:01.2
31:01.3

2021-11-26 14:17:19 - test_network_sriov_stress.py - [line:109] - root - INFO - Succssfully Gotten vf_id list:

2021-11-26 14:17:22 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2021-11-26 14:17:22 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2021-11-26 14:17:27 - test_network_sriov_stress.py - [line:162] - root - INFO - Successfuly modeprobe vfio-pci
2021-11-26 14:17:30 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 31:01.0
2021-11-26 14:17:31 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:17:36 - test_network_sriov_stress.py - [line:141] - root - INFO - Successfuly bound VF to vfio-pci
2021-11-26 14:17:39 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 31:01.1
2021-11-26 14:17:40 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:17:45 - test_network_sriov_stress.py - [line:141] - root - INFO - Successfuly bound VF to vfio-pci
2021-11-26 14:17:45 - test_network_sriov_stress.py - [line:381] - root - INFO - lspci -Dnn | grep 31:01.1
2021-11-26 14:17:48 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 31:01.1
2021-11-26 14:17:48 - sshInstance.py - [line:48] - root - INFO - 0000:31:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2021-11-26 14:17:53 - test_network_sriov_stress.py - [line:392] - root - INFO - Successfully get vf device id: 8086:1889
2021-11-26 14:17:56 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2021-11-26 14:17:56 - sshInstance.py - [line:48] - root - INFO - yes

2021-11-26 14:18:01 - test_network_sriov_stress.py - [line:170] - root - INFO - Default network is active? yes

2021-11-26 14:18:05 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:229299): [1;33mWARNING[0m **: [34m14:18:14.481[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:18:08 - test_network_sriov_stress.py - [line:202] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:229299): [1;33mWARNING[0m **: [34m14:18:14.481[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:18:08 - test_network_sriov_stress.py - [line:203] - root - ERROR - Failed to create a VM: 
2021-11-26 14:18:12 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:229357): [1;33mWARNING[0m **: [34m14:18:21.528[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2021-11-26 14:18:15 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW30CYP10 ~]# 
2021-11-26 14:18:18 - test_network_sriov_stress.py - [line:205] - root - INFO - Successfully created a VM: VMtest1
2021-11-26 14:18:22 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:229422): [1;33mWARNING[0m **: [34m14:18:31.541[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:18:25 - test_network_sriov_stress.py - [line:202] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:229422): [1;33mWARNING[0m **: [34m14:18:31.541[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:18:25 - test_network_sriov_stress.py - [line:203] - root - ERROR - Failed to create a VM: 
2021-11-26 14:18:29 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:229483): [1;33mWARNING[0m **: [34m14:18:38.531[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2021-11-26 14:18:32 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW30CYP10 ~]# 
2021-11-26 14:18:35 - test_network_sriov_stress.py - [line:205] - root - INFO - Successfully created a VM: VMtest2
2021-11-26 14:18:38 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:18:38 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:18:43 - test_network_sriov_stress.py - [line:221] - root - ERROR - not found IP of VMtest1
2021-11-26 14:19:46 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:19:46 - sshInstance.py - [line:48] - root - INFO - 192.168.122.51/24

2021-11-26 14:19:51 - test_network_sriov_stress.py - [line:216] - root - INFO - Successfully got VMtest1 IP: 192.168.122.51/24

2021-11-26 14:19:54 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:19:54 - sshInstance.py - [line:48] - root - INFO - 192.168.122.153/24

2021-11-26 14:19:59 - test_network_sriov_stress.py - [line:216] - root - INFO - Successfully got VMtest2 IP: 192.168.122.153/24

2021-11-26 14:19:59 - test_network_sriov_stress.py - [line:409] - root - INFO - ip of VM1: 192.168.122.51
2021-11-26 14:19:59 - test_network_sriov_stress.py - [line:410] - root - INFO - ip of VM1: 192.168.122.153
2021-11-26 14:20:03 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.51
PING 192.168.122.51 (192.168.122.51) 56(84) bytes of data.
64 bytes from 192.168.122.51: icmp_seq=1 ttl=64 time=0.112 ms
2021-11-26 14:20:04 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=2 ttl=64 time=0.075 ms
2021-11-26 14:20:05 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=3 ttl=64 time=0.157 ms
2021-11-26 14:20:06 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=4 ttl=64 time=0.072 ms
2021-11-26 14:20:07 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=5 ttl=64 time=0.068 ms

--- 192.168.122.51 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4093ms
rtt min/avg/max/mdev = 0.068/0.096/0.157/0.036 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:20:15 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.51
root@192.168.122.51's password: 
2021-11-26 14:20:23 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:20:30 AM EST
  System load:  0.18               Processes:             138
  Usage of /:   47.6% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.51
  Swap usage:   0%

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:15:06 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:20:31 - sshInstance.py - [line:89] - root - INFO - lspci -Dnn | grep "8086:1889" | awk '{print $1;}'
0000:00:05.0
root@localhost:~# 
2021-11-26 14:20:37 - test_network_sriov_stress.py - [line:306] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2021-11-26 14:20:42 - sshInstance.py - [line:89] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2021-11-26 14:20:47 - test_network_sriov_stress.py - [line:317] - root - INFO - Successfully got vf device name of vm1: ens5
2021-11-26 14:20:53 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2021-11-26 14:20:56 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens5
2021-11-26 14:21:01 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2021-11-26 14:21:09 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2021-11-26 14:21:17 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2021-11-26 14:21:25 - sshInstance.py - [line:89] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2021-11-26 14:21:33 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2021-11-26 14:21:41 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.51 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:21:48 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.153
PING 192.168.122.153 (192.168.122.153) 56(84) bytes of data.
64 bytes from 192.168.122.153: icmp_seq=1 ttl=64 time=0.140 ms
2021-11-26 14:21:49 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=2 ttl=64 time=0.097 ms
2021-11-26 14:21:50 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=3 ttl=64 time=0.097 ms
2021-11-26 14:21:51 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=4 ttl=64 time=0.076 ms
2021-11-26 14:21:52 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=5 ttl=64 time=0.066 ms

--- 192.168.122.153 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4104ms
rtt min/avg/max/mdev = 0.066/0.095/0.140/0.026 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:22:00 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.153
root@192.168.122.153's password: 
2021-11-26 14:22:08 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:22:15 AM EST
  System load:  0.08               Processes:             137
  Usage of /:   47.9% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.153
  Swap usage:   0%

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:13:01 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:22:16 - sshInstance.py - [line:89] - root - INFO - lspci -Dnn | grep "8086:1889" | awk '{print $1;}'
0000:00:05.0
root@localhost:~# 
2021-11-26 14:22:22 - test_network_sriov_stress.py - [line:306] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2021-11-26 14:22:27 - sshInstance.py - [line:89] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2021-11-26 14:22:32 - test_network_sriov_stress.py - [line:317] - root - INFO - Successfully got vf device name of vm1: ens5
2021-11-26 14:22:37 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2021-11-26 14:22:40 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens5
2021-11-26 14:22:45 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2021-11-26 14:22:53 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2021-11-26 14:23:01 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2021-11-26 14:23:09 - sshInstance.py - [line:89] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2021-11-26 14:23:17 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 684 (684.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2021-11-26 14:23:25 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.153 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:23:28 - test_network_sriov_stress.py - [line:428] - root - INFO - Ping two vms IP from SUT:
2021-11-26 14:23:32 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=4.90 ms
2021-11-26 14:23:33 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.046 ms
2021-11-26 14:23:34 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.052 ms
2021-11-26 14:23:35 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.073 ms
2021-11-26 14:23:36 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.041 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4113ms
rtt min/avg/max/mdev = 0.041/1.021/4.897/1.938 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:23:43 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.131 ms
2021-11-26 14:23:44 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.051 ms
2021-11-26 14:23:45 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.041 ms
2021-11-26 14:23:46 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.037 ms
2021-11-26 14:23:47 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.036 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4109ms
rtt min/avg/max/mdev = 0.036/0.059/0.131/0.036 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:23:50 - test_network_sriov_stress.py - [line:436] - root - INFO - ping VMtest2 IP from VMtest1
2021-11-26 14:23:54 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.51
PING 192.168.122.51 (192.168.122.51) 56(84) bytes of data.
64 bytes from 192.168.122.51: icmp_seq=1 ttl=64 time=0.142 ms
2021-11-26 14:23:55 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=2 ttl=64 time=0.105 ms
2021-11-26 14:23:56 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=3 ttl=64 time=0.092 ms
2021-11-26 14:23:57 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=4 ttl=64 time=0.075 ms
2021-11-26 14:23:58 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=5 ttl=64 time=0.066 ms

--- 192.168.122.51 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4103ms
rtt min/avg/max/mdev = 0.066/0.096/0.142/0.026 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:24:06 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.51
root@192.168.122.51's password: 
2021-11-26 14:24:14 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:24:20 AM EST
  System load:  0.24               Processes:             127
  Usage of /:   47.6% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.51
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:20:31 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:24:21 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.170 ms
2021-11-26 14:24:22 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.041 ms
2021-11-26 14:24:23 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.042 ms
2021-11-26 14:24:24 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.035 ms
2021-11-26 14:24:25 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.051 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4092ms
rtt min/avg/max/mdev = 0.035/0.067/0.170/0.051 ms
root@localhost:~# 
2021-11-26 14:25:04 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.51 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:25:07 - test_network_sriov_stress.py - [line:444] - root - INFO - ping VMtest2 IP from VMtest1
2021-11-26 14:25:11 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.11 192.168.10.10
PING 192.168.10.10 (192.168.10.10) from 192.168.10.11 : 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.042 ms
2021-11-26 14:25:12 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.010 ms
2021-11-26 14:25:13 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.009 ms
2021-11-26 14:25:14 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.020 ms
2021-11-26 14:25:15 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.025 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4073ms
rtt min/avg/max/mdev = 0.009/0.021/0.042/0.012 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:25:21 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens787f0/device/sriov_numvfs
2021-11-26 14:25:23 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:25:28 - test_network_sriov_stress.py - [line:237] - root - INFO - Successfully removed VFs from PF.
2021-11-26 14:25:31 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2021-11-26 14:25:32 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2021-11-26 14:25:37 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully shut down the VM: VMtest1
2021-11-26 14:25:40 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2021-11-26 14:25:40 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2021-11-26 14:25:45 - test_network_sriov_stress.py - [line:254] - root - INFO - Successfully removed the VM: VMtest1
2021-11-26 14:25:48 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2021-11-26 14:25:48 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2021-11-26 14:25:53 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully shut down the VM: VMtest2
2021-11-26 14:25:56 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2021-11-26 14:25:56 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2021-11-26 14:26:01 - test_network_sriov_stress.py - [line:254] - root - INFO - Successfully removed the VM: VMtest2
2021-11-26 14:26:01 - test_network_sriov_stress.py - [line:349] - root - INFO - 

********************************************************Stress Disable and Enable for 4 time when VF is Assigned VM guest.*************************************************************


2021-11-26 14:26:04 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens787f0 | awk '{print $1;}'
2021-11-26 14:26:05 - sshInstance.py - [line:48] - root - INFO - 0000:31:00.0

2021-11-26 14:26:10 - test_network_sriov_stress.py - [line:80] - root - INFO - pf_id was found: 0000:31:00.0

2021-11-26 14:26:10 - test_network_sriov_stress.py - [line:357] - root - INFO - format_pf_id is 0000\:31\:00.0

2021-11-26 14:26:10 - test_network_sriov_stress.py - [line:360] - root - INFO - pf_id_key: 31
2021-11-26 14:26:15 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 192.168.10.11
[root@WW30CYP10 ~]# 
2021-11-26 14:26:18 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens787f0
2021-11-26 14:26:21 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens787f0/device/sriov_numvfs
2021-11-26 14:26:21 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:26:26 - test_network_sriov_stress.py - [line:95] - root - INFO - Successfully Virtualized PF to VFs.
2021-11-26 14:26:29 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2021-11-26 14:26:29 - sshInstance.py - [line:48] - root - INFO - 31:01.0
31:01.1
31:01.2
31:01.3

2021-11-26 14:26:34 - test_network_sriov_stress.py - [line:109] - root - INFO - Succssfully Gotten vf_id list:

2021-11-26 14:26:37 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2021-11-26 14:26:37 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2021-11-26 14:26:42 - test_network_sriov_stress.py - [line:162] - root - INFO - Successfuly modeprobe vfio-pci
2021-11-26 14:26:45 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 31:01.0
2021-11-26 14:26:46 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:26:51 - test_network_sriov_stress.py - [line:141] - root - INFO - Successfuly bound VF to vfio-pci
2021-11-26 14:26:54 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 31:01.1
2021-11-26 14:26:55 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:27:00 - test_network_sriov_stress.py - [line:141] - root - INFO - Successfuly bound VF to vfio-pci
2021-11-26 14:27:00 - test_network_sriov_stress.py - [line:381] - root - INFO - lspci -Dnn | grep 31:01.1
2021-11-26 14:27:03 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 31:01.1
2021-11-26 14:27:03 - sshInstance.py - [line:48] - root - INFO - 0000:31:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2021-11-26 14:27:08 - test_network_sriov_stress.py - [line:392] - root - INFO - Successfully get vf device id: 8086:1889
2021-11-26 14:27:11 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2021-11-26 14:27:11 - sshInstance.py - [line:48] - root - INFO - yes

2021-11-26 14:27:16 - test_network_sriov_stress.py - [line:170] - root - INFO - Default network is active? yes

2021-11-26 14:27:20 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:231109): [1;33mWARNING[0m **: [34m14:27:29.279[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:27:23 - test_network_sriov_stress.py - [line:202] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:231109): [1;33mWARNING[0m **: [34m14:27:29.279[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:27:23 - test_network_sriov_stress.py - [line:203] - root - ERROR - Failed to create a VM: 
2021-11-26 14:27:27 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:231169): [1;33mWARNING[0m **: [34m14:27:36.296[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2021-11-26 14:27:30 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW30CYP10 ~]# 
2021-11-26 14:27:33 - test_network_sriov_stress.py - [line:205] - root - INFO - Successfully created a VM: VMtest1
2021-11-26 14:27:37 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:231232): [1;33mWARNING[0m **: [34m14:27:46.313[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:27:40 - test_network_sriov_stress.py - [line:202] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:231232): [1;33mWARNING[0m **: [34m14:27:46.313[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:27:40 - test_network_sriov_stress.py - [line:203] - root - ERROR - Failed to create a VM: 
2021-11-26 14:27:44 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:231294): [1;33mWARNING[0m **: [34m14:27:53.337[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2021-11-26 14:27:47 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW30CYP10 ~]# 
2021-11-26 14:27:50 - test_network_sriov_stress.py - [line:205] - root - INFO - Successfully created a VM: VMtest2
2021-11-26 14:27:53 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:27:53 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:27:58 - test_network_sriov_stress.py - [line:221] - root - ERROR - not found IP of VMtest1
2021-11-26 14:29:01 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:29:01 - sshInstance.py - [line:48] - root - INFO - 192.168.122.51/24

2021-11-26 14:29:06 - test_network_sriov_stress.py - [line:216] - root - INFO - Successfully got VMtest1 IP: 192.168.122.51/24

2021-11-26 14:29:09 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:29:09 - sshInstance.py - [line:48] - root - INFO - 192.168.122.153/24

2021-11-26 14:29:14 - test_network_sriov_stress.py - [line:216] - root - INFO - Successfully got VMtest2 IP: 192.168.122.153/24

2021-11-26 14:29:14 - test_network_sriov_stress.py - [line:409] - root - INFO - ip of VM1: 192.168.122.51
2021-11-26 14:29:14 - test_network_sriov_stress.py - [line:410] - root - INFO - ip of VM1: 192.168.122.153
2021-11-26 14:29:18 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.51
PING 192.168.122.51 (192.168.122.51) 56(84) bytes of data.
64 bytes from 192.168.122.51: icmp_seq=1 ttl=64 time=0.131 ms
2021-11-26 14:29:19 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=2 ttl=64 time=0.109 ms
2021-11-26 14:29:20 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=3 ttl=64 time=0.126 ms
2021-11-26 14:29:21 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=4 ttl=64 time=0.094 ms
2021-11-26 14:29:22 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=5 ttl=64 time=0.076 ms

--- 192.168.122.51 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4121ms
rtt min/avg/max/mdev = 0.076/0.107/0.131/0.021 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:29:30 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.51
root@192.168.122.51's password: 
2021-11-26 14:29:38 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:29:44 AM EST
  System load:  0.23               Processes:             134
  Usage of /:   47.6% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.51
  Swap usage:   0%

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:24:21 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:29:46 - sshInstance.py - [line:89] - root - INFO - lspci -Dnn | grep "8086:1889" | awk '{print $1;}'
0000:00:05.0
root@localhost:~# 
2021-11-26 14:29:52 - test_network_sriov_stress.py - [line:306] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2021-11-26 14:29:57 - sshInstance.py - [line:89] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2021-11-26 14:30:02 - test_network_sriov_stress.py - [line:317] - root - INFO - Successfully got vf device name of vm1: ens5
2021-11-26 14:30:07 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2021-11-26 14:30:10 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens5
2021-11-26 14:30:15 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2021-11-26 14:30:23 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2021-11-26 14:30:31 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2021-11-26 14:30:39 - sshInstance.py - [line:89] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2021-11-26 14:30:47 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2021-11-26 14:30:55 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.51 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:31:02 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.153
PING 192.168.122.153 (192.168.122.153) 56(84) bytes of data.
64 bytes from 192.168.122.153: icmp_seq=1 ttl=64 time=0.140 ms
2021-11-26 14:31:03 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=2 ttl=64 time=0.101 ms
2021-11-26 14:31:04 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=3 ttl=64 time=0.084 ms
2021-11-26 14:31:05 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=4 ttl=64 time=0.134 ms
2021-11-26 14:31:06 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=5 ttl=64 time=0.075 ms

--- 192.168.122.153 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4130ms
rtt min/avg/max/mdev = 0.075/0.106/0.140/0.029 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:31:14 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.153
root@192.168.122.153's password: 
2021-11-26 14:31:22 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:31:29 AM EST
  System load:  0.02               Processes:             140
  Usage of /:   48.0% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.153
  Swap usage:   0%

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:22:15 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:31:30 - sshInstance.py - [line:89] - root - INFO - lspci -Dnn | grep "8086:1889" | awk '{print $1;}'
0000:00:05.0
root@localhost:~# 
2021-11-26 14:31:36 - test_network_sriov_stress.py - [line:306] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2021-11-26 14:31:41 - sshInstance.py - [line:89] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2021-11-26 14:31:46 - test_network_sriov_stress.py - [line:317] - root - INFO - Successfully got vf device name of vm1: ens5
2021-11-26 14:31:51 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2021-11-26 14:31:54 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens5
2021-11-26 14:31:59 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2021-11-26 14:32:07 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2021-11-26 14:32:15 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2021-11-26 14:32:23 - sshInstance.py - [line:89] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2021-11-26 14:32:31 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2021-11-26 14:32:39 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.153 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:32:42 - test_network_sriov_stress.py - [line:428] - root - INFO - Ping two vms IP from SUT:
2021-11-26 14:32:46 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.192 ms
2021-11-26 14:32:47 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.043 ms
2021-11-26 14:32:48 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.046 ms
2021-11-26 14:32:49 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.123 ms
2021-11-26 14:32:50 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.035 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4079ms
rtt min/avg/max/mdev = 0.035/0.087/0.192/0.062 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:32:58 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.163 ms
2021-11-26 14:32:59 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.034 ms
2021-11-26 14:33:00 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.034 ms
2021-11-26 14:33:01 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.037 ms
2021-11-26 14:33:02 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.032 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4073ms
rtt min/avg/max/mdev = 0.032/0.060/0.163/0.051 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:33:05 - test_network_sriov_stress.py - [line:436] - root - INFO - ping VMtest2 IP from VMtest1
2021-11-26 14:33:09 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.51
PING 192.168.122.51 (192.168.122.51) 56(84) bytes of data.
64 bytes from 192.168.122.51: icmp_seq=1 ttl=64 time=0.128 ms
2021-11-26 14:33:10 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=2 ttl=64 time=0.128 ms
2021-11-26 14:33:11 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=3 ttl=64 time=0.161 ms
2021-11-26 14:33:12 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=4 ttl=64 time=0.124 ms
2021-11-26 14:33:13 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=5 ttl=64 time=0.087 ms

--- 192.168.122.51 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4131ms
rtt min/avg/max/mdev = 0.087/0.125/0.161/0.026 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:33:21 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.51
root@192.168.122.51's password: 
2021-11-26 14:33:29 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:33:35 AM EST
  System load:  0.0                Processes:             128
  Usage of /:   47.6% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.51
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:29:45 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:33:36 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=9.52 ms
2021-11-26 14:33:37 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.068 ms
2021-11-26 14:33:38 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.040 ms
2021-11-26 14:33:39 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.038 ms
2021-11-26 14:33:40 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.041 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4080ms
rtt min/avg/max/mdev = 0.038/1.941/9.520/3.789 ms
root@localhost:~# 
2021-11-26 14:34:19 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.51 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:34:22 - test_network_sriov_stress.py - [line:444] - root - INFO - ping VMtest2 IP from VMtest1
2021-11-26 14:34:26 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.11 192.168.10.10
PING 192.168.10.10 (192.168.10.10) from 192.168.10.11 : 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.050 ms
2021-11-26 14:34:27 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.010 ms
2021-11-26 14:34:28 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.008 ms
2021-11-26 14:34:29 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.028 ms
2021-11-26 14:34:30 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.021 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4102ms
rtt min/avg/max/mdev = 0.008/0.023/0.050/0.015 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:34:36 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens787f0/device/sriov_numvfs
2021-11-26 14:34:38 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:34:43 - test_network_sriov_stress.py - [line:237] - root - INFO - Successfully removed VFs from PF.
2021-11-26 14:34:46 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2021-11-26 14:34:47 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2021-11-26 14:34:52 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully shut down the VM: VMtest1
2021-11-26 14:34:55 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2021-11-26 14:34:55 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2021-11-26 14:35:00 - test_network_sriov_stress.py - [line:254] - root - INFO - Successfully removed the VM: VMtest1
2021-11-26 14:35:03 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2021-11-26 14:35:03 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2021-11-26 14:35:08 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully shut down the VM: VMtest2
2021-11-26 14:35:11 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2021-11-26 14:35:12 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2021-11-26 14:35:17 - test_network_sriov_stress.py - [line:254] - root - INFO - Successfully removed the VM: VMtest2
2021-11-26 14:35:17 - test_network_sriov_stress.py - [line:349] - root - INFO - 

********************************************************Stress Disable and Enable for 5 time when VF is Assigned VM guest.*************************************************************


2021-11-26 14:35:20 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens787f0 | awk '{print $1;}'
2021-11-26 14:35:20 - sshInstance.py - [line:48] - root - INFO - 0000:31:00.0

2021-11-26 14:35:25 - test_network_sriov_stress.py - [line:80] - root - INFO - pf_id was found: 0000:31:00.0

2021-11-26 14:35:25 - test_network_sriov_stress.py - [line:357] - root - INFO - format_pf_id is 0000\:31\:00.0

2021-11-26 14:35:25 - test_network_sriov_stress.py - [line:360] - root - INFO - pf_id_key: 31
2021-11-26 14:35:30 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 192.168.10.11
[root@WW30CYP10 ~]# 
2021-11-26 14:35:33 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens787f0
2021-11-26 14:35:36 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens787f0/device/sriov_numvfs
2021-11-26 14:35:36 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:35:41 - test_network_sriov_stress.py - [line:95] - root - INFO - Successfully Virtualized PF to VFs.
2021-11-26 14:35:44 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2021-11-26 14:35:44 - sshInstance.py - [line:48] - root - INFO - 31:01.0
31:01.1
31:01.2
31:01.3

2021-11-26 14:35:49 - test_network_sriov_stress.py - [line:109] - root - INFO - Succssfully Gotten vf_id list:

2021-11-26 14:35:52 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2021-11-26 14:35:53 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2021-11-26 14:35:58 - test_network_sriov_stress.py - [line:162] - root - INFO - Successfuly modeprobe vfio-pci
2021-11-26 14:36:01 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 31:01.0
2021-11-26 14:36:01 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:36:06 - test_network_sriov_stress.py - [line:141] - root - INFO - Successfuly bound VF to vfio-pci
2021-11-26 14:36:09 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 31:01.1
2021-11-26 14:36:10 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:36:15 - test_network_sriov_stress.py - [line:141] - root - INFO - Successfuly bound VF to vfio-pci
2021-11-26 14:36:15 - test_network_sriov_stress.py - [line:381] - root - INFO - lspci -Dnn | grep 31:01.1
2021-11-26 14:36:18 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 31:01.1
2021-11-26 14:36:18 - sshInstance.py - [line:48] - root - INFO - 0000:31:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2021-11-26 14:36:23 - test_network_sriov_stress.py - [line:392] - root - INFO - Successfully get vf device id: 8086:1889
2021-11-26 14:36:26 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2021-11-26 14:36:26 - sshInstance.py - [line:48] - root - INFO - yes

2021-11-26 14:36:31 - test_network_sriov_stress.py - [line:170] - root - INFO - Default network is active? yes

2021-11-26 14:36:35 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:232754): [1;33mWARNING[0m **: [34m14:36:44.513[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:36:38 - test_network_sriov_stress.py - [line:202] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:232754): [1;33mWARNING[0m **: [34m14:36:44.513[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:36:38 - test_network_sriov_stress.py - [line:203] - root - ERROR - Failed to create a VM: 
2021-11-26 14:36:42 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:232812): [1;33mWARNING[0m **: [34m14:36:51.537[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2021-11-26 14:36:45 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW30CYP10 ~]# 
2021-11-26 14:36:48 - test_network_sriov_stress.py - [line:205] - root - INFO - Successfully created a VM: VMtest1
2021-11-26 14:36:52 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:232875): [1;33mWARNING[0m **: [34m14:37:01.559[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:36:55 - test_network_sriov_stress.py - [line:202] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:232875): [1;33mWARNING[0m **: [34m14:37:01.559[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:36:55 - test_network_sriov_stress.py - [line:203] - root - ERROR - Failed to create a VM: 
2021-11-26 14:36:59 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:232944): [1;33mWARNING[0m **: [34m14:37:08.558[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2021-11-26 14:37:02 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW30CYP10 ~]# 
2021-11-26 14:37:05 - test_network_sriov_stress.py - [line:205] - root - INFO - Successfully created a VM: VMtest2
2021-11-26 14:37:08 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:37:08 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:37:13 - test_network_sriov_stress.py - [line:221] - root - ERROR - not found IP of VMtest1
2021-11-26 14:38:16 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:38:16 - sshInstance.py - [line:48] - root - INFO - 192.168.122.51/24

2021-11-26 14:38:21 - test_network_sriov_stress.py - [line:216] - root - INFO - Successfully got VMtest1 IP: 192.168.122.51/24

2021-11-26 14:38:24 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:38:24 - sshInstance.py - [line:48] - root - INFO - 192.168.122.153/24

2021-11-26 14:38:29 - test_network_sriov_stress.py - [line:216] - root - INFO - Successfully got VMtest2 IP: 192.168.122.153/24

2021-11-26 14:38:29 - test_network_sriov_stress.py - [line:409] - root - INFO - ip of VM1: 192.168.122.51
2021-11-26 14:38:29 - test_network_sriov_stress.py - [line:410] - root - INFO - ip of VM1: 192.168.122.153
2021-11-26 14:38:33 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.51
PING 192.168.122.51 (192.168.122.51) 56(84) bytes of data.
64 bytes from 192.168.122.51: icmp_seq=1 ttl=64 time=0.106 ms
2021-11-26 14:38:34 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=2 ttl=64 time=0.114 ms
2021-11-26 14:38:35 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=3 ttl=64 time=0.081 ms
2021-11-26 14:38:36 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=4 ttl=64 time=0.084 ms
2021-11-26 14:38:37 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=5 ttl=64 time=0.087 ms

--- 192.168.122.51 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4094ms
rtt min/avg/max/mdev = 0.081/0.094/0.114/0.015 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:38:46 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.51
root@192.168.122.51's password: 
2021-11-26 14:38:54 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:39:01 AM EST
  System load:  0.09               Processes:             141
  Usage of /:   47.7% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.51
  Swap usage:   0%

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:33:35 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:39:02 - sshInstance.py - [line:89] - root - INFO - lspci -Dnn | grep "8086:1889" | awk '{print $1;}'
0000:00:05.0
root@localhost:~# 
2021-11-26 14:39:08 - test_network_sriov_stress.py - [line:306] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2021-11-26 14:39:13 - sshInstance.py - [line:89] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2021-11-26 14:39:18 - test_network_sriov_stress.py - [line:317] - root - INFO - Successfully got vf device name of vm1: ens5
2021-11-26 14:39:23 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2021-11-26 14:39:26 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens5
2021-11-26 14:39:31 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2021-11-26 14:39:39 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2021-11-26 14:39:47 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2021-11-26 14:39:55 - sshInstance.py - [line:89] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2021-11-26 14:40:03 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 346 (346.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2021-11-26 14:40:11 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.51 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:40:18 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.153
PING 192.168.122.153 (192.168.122.153) 56(84) bytes of data.
64 bytes from 192.168.122.153: icmp_seq=1 ttl=64 time=0.152 ms
2021-11-26 14:40:19 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=2 ttl=64 time=0.111 ms
2021-11-26 14:40:20 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=3 ttl=64 time=0.085 ms
2021-11-26 14:40:21 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=4 ttl=64 time=0.086 ms
2021-11-26 14:40:22 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=5 ttl=64 time=0.069 ms

--- 192.168.122.153 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4106ms
rtt min/avg/max/mdev = 0.069/0.100/0.152/0.031 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:40:30 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.153
root@192.168.122.153's password: 
2021-11-26 14:40:38 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:40:45 AM EST
  System load:  0.03               Processes:             138
  Usage of /:   48.0% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.153
  Swap usage:   0%

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:31:29 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:40:46 - sshInstance.py - [line:89] - root - INFO - lspci -Dnn | grep "8086:1889" | awk '{print $1;}'
0000:00:05.0
root@localhost:~# 
2021-11-26 14:40:52 - test_network_sriov_stress.py - [line:306] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2021-11-26 14:40:57 - sshInstance.py - [line:89] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2021-11-26 14:41:02 - test_network_sriov_stress.py - [line:317] - root - INFO - Successfully got vf device name of vm1: ens5
2021-11-26 14:41:07 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2021-11-26 14:41:10 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens5
2021-11-26 14:41:15 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2021-11-26 14:41:23 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2021-11-26 14:41:31 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2021-11-26 14:41:39 - sshInstance.py - [line:89] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2021-11-26 14:41:47 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2021-11-26 14:41:55 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.153 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:41:58 - test_network_sriov_stress.py - [line:428] - root - INFO - Ping two vms IP from SUT:
2021-11-26 14:42:02 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=11.3 ms
2021-11-26 14:42:03 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.054 ms
2021-11-26 14:42:04 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.031 ms
2021-11-26 14:42:05 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.048 ms
2021-11-26 14:42:06 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.042 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4053ms
rtt min/avg/max/mdev = 0.031/2.294/11.298/4.502 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:42:13 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.154 ms
2021-11-26 14:42:14 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.051 ms
2021-11-26 14:42:15 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.039 ms
2021-11-26 14:42:16 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.039 ms
2021-11-26 14:42:17 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.035 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4113ms
rtt min/avg/max/mdev = 0.035/0.063/0.154/0.046 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:42:20 - test_network_sriov_stress.py - [line:436] - root - INFO - ping VMtest2 IP from VMtest1
2021-11-26 14:42:24 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.51
PING 192.168.122.51 (192.168.122.51) 56(84) bytes of data.
64 bytes from 192.168.122.51: icmp_seq=1 ttl=64 time=0.119 ms
2021-11-26 14:42:25 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=2 ttl=64 time=0.124 ms
2021-11-26 14:42:26 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=3 ttl=64 time=0.143 ms
2021-11-26 14:42:27 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=4 ttl=64 time=0.083 ms
2021-11-26 14:42:28 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=5 ttl=64 time=0.079 ms

--- 192.168.122.51 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4107ms
rtt min/avg/max/mdev = 0.079/0.109/0.143/0.027 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:42:36 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.51
root@192.168.122.51's password: 
2021-11-26 14:42:44 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:42:51 AM EST
  System load:  0.16               Processes:             132
  Usage of /:   47.7% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.51
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:39:01 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:42:51 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.144 ms
2021-11-26 14:42:52 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.040 ms
2021-11-26 14:42:53 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.033 ms
2021-11-26 14:42:54 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.032 ms
2021-11-26 14:42:55 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.071 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4083ms
rtt min/avg/max/mdev = 0.032/0.064/0.144/0.042 ms
root@localhost:~# 
2021-11-26 14:43:34 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.51 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:43:37 - test_network_sriov_stress.py - [line:444] - root - INFO - ping VMtest2 IP from VMtest1
2021-11-26 14:43:41 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.11 192.168.10.10
PING 192.168.10.10 (192.168.10.10) from 192.168.10.11 : 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.044 ms
2021-11-26 14:43:42 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.014 ms
2021-11-26 14:43:43 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.009 ms
2021-11-26 14:43:44 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.032 ms
2021-11-26 14:43:45 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.020 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4119ms
rtt min/avg/max/mdev = 0.009/0.023/0.044/0.014 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:43:51 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens787f0/device/sriov_numvfs
2021-11-26 14:43:53 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:43:58 - test_network_sriov_stress.py - [line:237] - root - INFO - Successfully removed VFs from PF.
2021-11-26 14:44:01 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2021-11-26 14:44:02 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2021-11-26 14:44:07 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully shut down the VM: VMtest1
2021-11-26 14:44:10 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2021-11-26 14:44:10 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2021-11-26 14:44:15 - test_network_sriov_stress.py - [line:254] - root - INFO - Successfully removed the VM: VMtest1
2021-11-26 14:44:18 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2021-11-26 14:44:19 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2021-11-26 14:44:24 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully shut down the VM: VMtest2
2021-11-26 14:44:27 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2021-11-26 14:44:27 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2021-11-26 14:44:32 - test_network_sriov_stress.py - [line:254] - root - INFO - Successfully removed the VM: VMtest2
.2021-11-26 14:44:32 - test_network_sriov_stress.py - [line:52] - root - INFO - this is the teardown of Test_Network_SRIOV_Stress.
2021-11-26 14:44:35 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2021-11-26 14:44:35 - sshInstance.py - [line:48] - root - INFO - 

2021-11-26 14:44:40 - test_network_sriov_stress.py - [line:249] - root - ERROR - Failed to shut down the VM VMtest2
2021-11-26 14:44:43 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2021-11-26 14:44:43 - sshInstance.py - [line:48] - root - INFO - 

2021-11-26 14:44:48 - test_network_sriov_stress.py - [line:249] - root - ERROR - Failed to shut down the VM VMtest1
2021-11-26 14:44:48 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2021-11-26 14:44:48 - test_network_sriov_stress.py - [line:57] - root - INFO - =============================================Finished run the test case===============================================
2021-11-26 14:44:48 - NicTestFixture.py - [line:28] - root - INFO - Starting to run test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[ubuntu20.04_2.img-ubuntu20.04.img]
2021-11-26 14:44:48 - NicTestFixture.py - [line:29] - root - INFO - setup log for testing in the fixture class fbefore
2021-11-26 14:44:48 - test_network_sriov_stress.py - [line:30] - root - INFO - SSH SUT and setup configurations in the setup function.
2021-11-26 14:44:48 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2021-11-26 14:44:48 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (publickey) failed.
2021-11-26 14:44:48 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2021-11-26 14:44:48 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.157
2021-11-26 14:44:51 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens787f0 | awk '{print $1;}'
2021-11-26 14:44:52 - sshInstance.py - [line:48] - root - INFO - 0000:31:00.0

2021-11-26 14:44:57 - test_network_sriov_stress.py - [line:80] - root - INFO - pf_id was found: 0000:31:00.0

2021-11-26 14:44:57 - test_network_sriov_stress.py - [line:467] - root - INFO - format_pf_id is 0000\:31\:00.0

2021-11-26 14:44:57 - test_network_sriov_stress.py - [line:470] - root - INFO - pf_id_key: 31
2021-11-26 14:45:02 - sshInstance.py - [line:89] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Nov 26 13:58:24 2021 from 10.239.129.147
[root@WW30CYP10 ~]# ifconfig ens787f0 192.168.10.11
[root@WW30CYP10 ~]# 
2021-11-26 14:45:05 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens787f0
2021-11-26 14:45:08 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens787f0/device/sriov_numvfs
2021-11-26 14:45:08 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:45:13 - test_network_sriov_stress.py - [line:95] - root - INFO - Successfully Virtualized PF to VFs.
2021-11-26 14:45:16 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2021-11-26 14:45:16 - sshInstance.py - [line:48] - root - INFO - 31:01.0
31:01.1
31:01.2
31:01.3

2021-11-26 14:45:21 - test_network_sriov_stress.py - [line:109] - root - INFO - Succssfully Gotten vf_id list:

2021-11-26 14:45:24 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2021-11-26 14:45:24 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2021-11-26 14:45:29 - test_network_sriov_stress.py - [line:162] - root - INFO - Successfuly modeprobe vfio-pci
2021-11-26 14:45:32 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 31:01.0
2021-11-26 14:45:33 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:45:38 - test_network_sriov_stress.py - [line:141] - root - INFO - Successfuly bound VF to vfio-pci
2021-11-26 14:45:41 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 31:01.1
2021-11-26 14:45:42 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:45:47 - test_network_sriov_stress.py - [line:141] - root - INFO - Successfuly bound VF to vfio-pci
2021-11-26 14:45:47 - test_network_sriov_stress.py - [line:493] - root - INFO - lspci -Dnn | grep 31:01.1
2021-11-26 14:45:50 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 31:01.1
2021-11-26 14:45:50 - sshInstance.py - [line:48] - root - INFO - 0000:31:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2021-11-26 14:45:55 - test_network_sriov_stress.py - [line:504] - root - INFO - Successfully get vf device id: 8086:1889
2021-11-26 14:45:58 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2021-11-26 14:45:58 - sshInstance.py - [line:48] - root - INFO - yes

2021-11-26 14:46:03 - test_network_sriov_stress.py - [line:170] - root - INFO - Default network is active? yes

2021-11-26 14:46:07 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:234250): [1;33mWARNING[0m **: [34m14:46:16.055[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:46:10 - test_network_sriov_stress.py - [line:202] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:234250): [1;33mWARNING[0m **: [34m14:46:16.055[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:46:10 - test_network_sriov_stress.py - [line:203] - root - ERROR - Failed to create a VM: 
2021-11-26 14:46:14 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_0 --boot hd --disk path=/home//image/ubuntu20.04_2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port==5900 --noautoconsole

** (process:234310): [1;33mWARNING[0m **: [34m14:46:23.062[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2021-11-26 14:46:17 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW30CYP10 ~]# 
2021-11-26 14:46:20 - test_network_sriov_stress.py - [line:205] - root - INFO - Successfully created a VM: VMtest1
2021-11-26 14:46:24 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:234376): [1;33mWARNING[0m **: [34m14:46:33.074[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:46:27 - test_network_sriov_stress.py - [line:202] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:234376): [1;33mWARNING[0m **: [34m14:46:33.074[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:31:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW30CYP10 ~]# 
2021-11-26 14:46:27 - test_network_sriov_stress.py - [line:203] - root - ERROR - Failed to create a VM: 
2021-11-26 14:46:31 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_31_01_1 --boot hd --disk path=/home//image/ubuntu20.04.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=59901 --noautoconsole

** (process:234438): [1;33mWARNING[0m **: [34m14:46:40.089[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2021-11-26 14:46:34 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW30CYP10 ~]# 
2021-11-26 14:46:37 - test_network_sriov_stress.py - [line:205] - root - INFO - Successfully created a VM: VMtest2
2021-11-26 14:46:40 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:46:40 - sshInstance.py - [line:48] - root - INFO - 
2021-11-26 14:46:45 - test_network_sriov_stress.py - [line:221] - root - ERROR - not found IP of VMtest1
2021-11-26 14:47:48 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:47:48 - sshInstance.py - [line:48] - root - INFO - 192.168.122.51/24

2021-11-26 14:47:53 - test_network_sriov_stress.py - [line:216] - root - INFO - Successfully got VMtest1 IP: 192.168.122.51/24

2021-11-26 14:47:56 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2021-11-26 14:47:56 - sshInstance.py - [line:48] - root - INFO - 192.168.122.153/24

2021-11-26 14:48:01 - test_network_sriov_stress.py - [line:216] - root - INFO - Successfully got VMtest2 IP: 192.168.122.153/24

2021-11-26 14:48:05 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.51
PING 192.168.122.51 (192.168.122.51) 56(84) bytes of data.
64 bytes from 192.168.122.51: icmp_seq=1 ttl=64 time=0.173 ms
2021-11-26 14:48:06 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=2 ttl=64 time=0.104 ms
2021-11-26 14:48:07 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=3 ttl=64 time=0.143 ms
2021-11-26 14:48:08 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=4 ttl=64 time=0.085 ms
2021-11-26 14:48:09 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=5 ttl=64 time=0.143 ms

--- 192.168.122.51 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4097ms
rtt min/avg/max/mdev = 0.085/0.129/0.173/0.033 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:48:17 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.51
root@192.168.122.51's password: 
2021-11-26 14:48:25 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:48:31 AM EST
  System load:  0.03               Processes:             136
  Usage of /:   47.7% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.51
  Swap usage:   0%

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:42:51 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:48:33 - sshInstance.py - [line:89] - root - INFO - lspci -Dnn | grep "8086:1889" | awk '{print $1;}'
0000:00:05.0
root@localhost:~# 
2021-11-26 14:48:39 - test_network_sriov_stress.py - [line:306] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2021-11-26 14:48:44 - sshInstance.py - [line:89] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2021-11-26 14:48:49 - test_network_sriov_stress.py - [line:317] - root - INFO - Successfully got vf device name of vm1: ens5
2021-11-26 14:48:54 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2021-11-26 14:48:57 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens5
2021-11-26 14:49:02 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2021-11-26 14:49:10 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2021-11-26 14:49:18 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2021-11-26 14:49:26 - sshInstance.py - [line:89] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2021-11-26 14:49:34 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 342 (342.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 8  bytes 696 (696.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2021-11-26 14:49:42 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.51 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:49:49 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.153
PING 192.168.122.153 (192.168.122.153) 56(84) bytes of data.
64 bytes from 192.168.122.153: icmp_seq=1 ttl=64 time=0.132 ms
2021-11-26 14:49:50 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=2 ttl=64 time=0.088 ms
2021-11-26 14:49:51 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=3 ttl=64 time=0.074 ms
2021-11-26 14:49:52 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=4 ttl=64 time=0.124 ms
2021-11-26 14:49:53 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.153: icmp_seq=5 ttl=64 time=0.084 ms

--- 192.168.122.153 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4111ms
rtt min/avg/max/mdev = 0.074/0.100/0.132/0.024 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:50:01 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.153
root@192.168.122.153's password: 
2021-11-26 14:50:09 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:50:15 AM EST
  System load:  0.02               Processes:             137
  Usage of /:   48.1% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.153
  Swap usage:   0%

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:40:45 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:50:17 - sshInstance.py - [line:89] - root - INFO - lspci -Dnn | grep "8086:1889" | awk '{print $1;}'
0000:00:05.0
root@localhost:~# 
2021-11-26 14:50:23 - test_network_sriov_stress.py - [line:306] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2021-11-26 14:50:28 - sshInstance.py - [line:89] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2021-11-26 14:50:33 - test_network_sriov_stress.py - [line:317] - root - INFO - Successfully got vf device name of vm1: ens5
2021-11-26 14:50:38 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2021-11-26 14:50:41 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully assigned ip to ethernet: ens5
2021-11-26 14:50:46 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2021-11-26 14:50:54 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2021-11-26 14:51:02 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2021-11-26 14:51:10 - sshInstance.py - [line:89] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2021-11-26 14:51:18 - sshInstance.py - [line:89] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 696 (696.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2021-11-26 14:51:26 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.153 closed.
[root@WW30CYP10 ~]# 
2021-11-26 14:51:33 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.51
PING 192.168.122.51 (192.168.122.51) 56(84) bytes of data.
64 bytes from 192.168.122.51: icmp_seq=1 ttl=64 time=0.152 ms
2021-11-26 14:51:34 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=2 ttl=64 time=0.081 ms
2021-11-26 14:51:35 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=3 ttl=64 time=0.099 ms
2021-11-26 14:51:36 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=4 ttl=64 time=0.108 ms
2021-11-26 14:51:37 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.51: icmp_seq=5 ttl=64 time=0.074 ms

--- 192.168.122.51 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4130ms
rtt min/avg/max/mdev = 0.074/0.102/0.152/0.030 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:51:45 - sshInstance.py - [line:89] - root - INFO - ssh root@192.168.122.51
root@192.168.122.51's password: 
2021-11-26 14:51:53 - sshInstance.py - [line:89] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Fri 26 Nov 2021 01:52:00 AM EST
  System load:  0.0                Processes:             137
  Usage of /:   47.7% of 19.07GB   Users logged in:       0
  Memory usage: 30%                IPv4 address for ens3: 192.168.122.51
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

366 updates can be installed immediately.
222 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Fri Nov 26 01:48:32 2021 from 192.168.122.1
root@localhost:~# 
2021-11-26 14:52:01 - sshInstance.py - [line:89] - root - INFO - nohup ping -w 60 192.168.10.11 > ping_sut1.txt &
[1] 1049
root@localhost:~# 
root@localhost:~# nohup: ignoring input and redirecting stderr to stdout

2021-11-26 14:52:09 - sshInstance.py - [line:89] - root - INFO - nohup ping6 -I ens5 -w 60 fe80::b696:91ff:fe9c:f760 >ping6_sut1.txt &
[2] 1053
root@localhost:~# 
root@localhost:~# nohup: ignoring input and redirecting stderr to stdout

2021-11-26 14:52:17 - sshInstance.py - [line:89] - root - INFO - nohup ping -w 60 192.168.10.13 > ping_vm2.txt &
[3] 1055
root@localhost:~# 
root@localhost:~# nohup: ignoring input and redirecting stderr to stdout

2021-11-26 14:52:25 - sshInstance.py - [line:89] - root - INFO - nohup ping6 -I ens5 -w 60 fe80::1034:56ff:fe78:90ab >ping6_vm2.txt &
[4] 1056
root@localhost:~# 
root@localhost:~# nohup: ignoring input and redirecting stderr to stdout

2021-11-26 14:52:33 - sshInstance.py - [line:89] - root - INFO - nohup ping -w 60 192.168.10.10 > ping_sut2.txt &
[5] 1057
root@localhost:~# 
root@localhost:~# nohup: ignoring input and redirecting stderr to stdout

2021-11-26 14:52:41 - sshInstance.py - [line:89] - root - INFO - nohup ping6 -I ens5 -w 60 fe80::b696:91ff:fe9c:f762 >ping6_sut2.txt &
[6] 1058
root@localhost:~# 
root@localhost:~# nohup: ignoring input and redirecting stderr to stdout

2021-11-26 14:52:44 - test_network_sriov_stress.py - [line:567] - root - INFO - ---ping end -----
2021-11-26 14:52:49 - sshInstance.py - [line:89] - root - INFO - tail -n 10 /root/ping_sut1.txt
64 bytes from 192.168.10.11: icmp_seq=38 ttl=64 time=0.030 ms
64 bytes from 192.168.10.11: icmp_seq=39 ttl=64 time=0.031 ms
64 bytes from 192.168.10.11: icmp_seq=40 ttl=64 time=0.028 ms
64 bytes from 192.168.10.11: icmp_seq=41 ttl=64 time=0.030 ms
64 bytes from 192.168.10.11: icmp_seq=42 ttl=64 time=0.028 ms
64 bytes from 192.168.10.11: icmp_seq=43 ttl=64 time=0.028 ms
64 bytes from 192.168.10.11: icmp_seq=44 ttl=64 time=0.028 ms
64 bytes from 192.168.10.11: icmp_seq=45 ttl=64 time=0.034 ms
64 bytes from 192.168.10.11: icmp_seq=46 ttl=64 time=0.028 ms
64 bytes from 192.168.10.11: icmp_seq=47 ttl=64 time=0.027 ms
root@localhost:~# 
2021-11-26 14:52:57 - sshInstance.py - [line:89] - root - INFO - tail -n 10 /root/ping6_sut1.txt
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=38 ttl=64 time=0.029 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=39 ttl=64 time=0.029 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=40 ttl=64 time=0.029 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=41 ttl=64 time=0.031 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=42 ttl=64 time=0.025 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=43 ttl=64 time=0.029 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=44 ttl=64 time=0.025 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=45 ttl=64 time=0.026 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=46 ttl=64 time=0.031 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=47 ttl=64 time=0.046 ms
root@localhost:~# 
2021-11-26 14:53:05 - sshInstance.py - [line:89] - root - INFO - tail -n 10 /root/ping_vm2.txt
64 bytes from 192.168.10.13: icmp_seq=38 ttl=64 time=0.038 ms
64 bytes from 192.168.10.13: icmp_seq=39 ttl=64 time=0.051 ms
64 bytes from 192.168.10.13: icmp_seq=40 ttl=64 time=0.052 ms
64 bytes from 192.168.10.13: icmp_seq=41 ttl=64 time=0.037 ms
64 bytes from 192.168.10.13: icmp_seq=42 ttl=64 time=0.032 ms
64 bytes from 192.168.10.13: icmp_seq=43 ttl=64 time=0.035 ms
64 bytes from 192.168.10.13: icmp_seq=44 ttl=64 time=0.050 ms
64 bytes from 192.168.10.13: icmp_seq=45 ttl=64 time=0.030 ms
64 bytes from 192.168.10.13: icmp_seq=46 ttl=64 time=0.031 ms
64 bytes from 192.168.10.13: icmp_seq=47 ttl=64 time=0.031 ms
[1]   Done                    nohup ping -w 60 192.168.10.11 > ping_sut1.txt
root@localhost:~# 
2021-11-26 14:53:13 - sshInstance.py - [line:89] - root - INFO - tail -n 10 /root/ping6_vm2.txt
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=38 ttl=64 time=0.029 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=39 ttl=64 time=0.034 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=40 ttl=64 time=0.052 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=41 ttl=64 time=0.042 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=42 ttl=64 time=0.035 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=43 ttl=64 time=0.036 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=44 ttl=64 time=0.038 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=45 ttl=64 time=0.048 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=46 ttl=64 time=0.036 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=47 ttl=64 time=0.036 ms
[2]   Done                    nohup ping6 -I ens5 -w 60 fe80::b696:91ff:fe9c:f760 > ping6_sut1.txt
root@localhost:~# 
2021-11-26 14:53:21 - sshInstance.py - [line:89] - root - INFO - tail -n 10 /root/ping_sut2.txt
64 bytes from 192.168.10.10: icmp_seq=38 ttl=64 time=0.035 ms
64 bytes from 192.168.10.10: icmp_seq=39 ttl=64 time=0.036 ms
64 bytes from 192.168.10.10: icmp_seq=40 ttl=64 time=0.031 ms
64 bytes from 192.168.10.10: icmp_seq=41 ttl=64 time=0.038 ms
64 bytes from 192.168.10.10: icmp_seq=42 ttl=64 time=0.041 ms
64 bytes from 192.168.10.10: icmp_seq=43 ttl=64 time=0.032 ms
64 bytes from 192.168.10.10: icmp_seq=44 ttl=64 time=0.032 ms
64 bytes from 192.168.10.10: icmp_seq=45 ttl=64 time=0.034 ms
64 bytes from 192.168.10.10: icmp_seq=46 ttl=64 time=0.032 ms
64 bytes from 192.168.10.10: icmp_seq=47 ttl=64 time=0.044 ms
[3]   Done                    nohup ping -w 60 192.168.10.13 > ping_vm2.txt
root@localhost:~# 
2021-11-26 14:53:29 - sshInstance.py - [line:89] - root - INFO - tail -n 10 /root/ping6_sut2.txt
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=38 ttl=64 time=0.030 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=39 ttl=64 time=0.033 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=40 ttl=64 time=0.033 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=41 ttl=64 time=0.039 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=42 ttl=64 time=0.057 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=43 ttl=64 time=0.030 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=44 ttl=64 time=0.036 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=45 ttl=64 time=0.038 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=46 ttl=64 time=0.031 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=47 ttl=64 time=0.033 ms
[4]   Done                    nohup ping6 -I ens5 -w 60 fe80::1034:56ff:fe78:90ab > ping6_vm2.txt
root@localhost:~# 
2021-11-26 14:53:47 - sshInstance.py - [line:89] - root - INFO - tail -n 10 /root/ping_sut1.txt
64 bytes from 192.168.10.11: icmp_seq=54 ttl=64 time=0.029 ms
64 bytes from 192.168.10.11: icmp_seq=55 ttl=64 time=0.037 ms
64 bytes from 192.168.10.11: icmp_seq=56 ttl=64 time=0.043 ms
64 bytes from 192.168.10.11: icmp_seq=57 ttl=64 time=0.033 ms
64 bytes from 192.168.10.11: icmp_seq=58 ttl=64 time=0.030 ms
64 bytes from 192.168.10.11: icmp_seq=59 ttl=64 time=0.029 ms
--- 192.168.10.11 ping statistics ---
59 packets transmitted, 59 received, 0% packet loss, time 59371ms
rtt min/avg/max/mdev = 0.027/0.136/6.117/0.785 ms
[5]-  Done                    nohup ping -w 60 192.168.10.10 > ping_sut2.txt
[6]+  Done                    nohup ping6 -I ens5 -w 60 fe80::b696:91ff:fe9c:f762 > ping6_sut2.txt
root@localhost:~# 
2021-11-26 14:53:55 - sshInstance.py - [line:89] - root - INFO - tail -n 10 /root/ping6_sut1.txt
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=54 ttl=64 time=0.025 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=55 ttl=64 time=0.026 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=56 ttl=64 time=0.043 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=57 ttl=64 time=0.036 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=58 ttl=64 time=0.027 ms
64 bytes from fe80::b696:91ff:fe9c:f760%ens5: icmp_seq=59 ttl=64 time=0.029 ms
--- fe80::b696:91ff:fe9c:f760 ping statistics ---
59 packets transmitted, 59 received, 0% packet loss, time 59396ms
rtt min/avg/max/mdev = 0.025/0.035/0.195/0.022 ms
root@localhost:~# 
2021-11-26 14:54:03 - sshInstance.py - [line:89] - root - INFO - tail -n 10 /root/ping_vm2.txt
64 bytes from 192.168.10.13: icmp_seq=54 ttl=64 time=0.027 ms
64 bytes from 192.168.10.13: icmp_seq=55 ttl=64 time=0.028 ms
64 bytes from 192.168.10.13: icmp_seq=56 ttl=64 time=0.031 ms
64 bytes from 192.168.10.13: icmp_seq=57 ttl=64 time=0.030 ms
64 bytes from 192.168.10.13: icmp_seq=58 ttl=64 time=0.033 ms
64 bytes from 192.168.10.13: icmp_seq=59 ttl=64 time=0.031 ms
--- 192.168.10.13 ping statistics ---
59 packets transmitted, 59 received, 0% packet loss, time 59356ms
rtt min/avg/max/mdev = 0.027/0.100/3.896/0.498 ms
root@localhost:~# 
2021-11-26 14:54:11 - sshInstance.py - [line:89] - root - INFO - tail -n 10 /root/ping6_vm2.txt
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=54 ttl=64 time=0.029 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=55 ttl=64 time=0.033 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=56 ttl=64 time=0.047 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=57 ttl=64 time=0.037 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=58 ttl=64 time=0.034 ms
64 bytes from fe80::1034:56ff:fe78:90ab%ens5: icmp_seq=59 ttl=64 time=0.033 ms
--- fe80::1034:56ff:fe78:90ab ping statistics ---
59 packets transmitted, 59 received, 0% packet loss, time 59379ms
rtt min/avg/max/mdev = 0.029/0.039/0.175/0.020 ms
root@localhost:~# 
2021-11-26 14:54:19 - sshInstance.py - [line:89] - root - INFO - tail -n 10 /root/ping_sut2.txt
64 bytes from 192.168.10.10: icmp_seq=54 ttl=64 time=0.038 ms
64 bytes from 192.168.10.10: icmp_seq=55 ttl=64 time=0.033 ms
64 bytes from 192.168.10.10: icmp_seq=56 ttl=64 time=0.038 ms
64 bytes from 192.168.10.10: icmp_seq=57 ttl=64 time=0.050 ms
64 bytes from 192.168.10.10: icmp_seq=58 ttl=64 time=0.039 ms
64 bytes from 192.168.10.10: icmp_seq=59 ttl=64 time=0.036 ms
--- 192.168.10.10 ping statistics ---
59 packets transmitted, 59 received, 0% packet loss, time 59371ms
rtt min/avg/max/mdev = 0.029/0.036/0.070/0.007 ms
root@localhost:~# 
2021-11-26 14:54:27 - sshInstance.py - [line:89] - root - INFO - tail -n 10 /root/ping6_sut2.txt
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=54 ttl=64 time=0.029 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=55 ttl=64 time=0.033 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=56 ttl=64 time=0.029 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=57 ttl=64 time=0.032 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=58 ttl=64 time=0.031 ms
64 bytes from fe80::b696:91ff:fe9c:f762%ens5: icmp_seq=59 ttl=64 time=0.032 ms
--- fe80::b696:91ff:fe9c:f762 ping statistics ---
59 packets transmitted, 59 received, 0% packet loss, time 59394ms
rtt min/avg/max/mdev = 0.027/0.036/0.123/0.013 ms
root@localhost:~# 
2021-11-26 14:54:30 - test_network_sriov_stress.py - [line:614] - root - INFO - Successfully ping sut1
2021-11-26 14:54:30 - test_network_sriov_stress.py - [line:614] - root - INFO - Successfully ping6 sut1
2021-11-26 14:54:30 - test_network_sriov_stress.py - [line:614] - root - INFO - Successfully ping vm2
2021-11-26 14:54:30 - test_network_sriov_stress.py - [line:614] - root - INFO - Successfully ping6 vm2
2021-11-26 14:54:30 - test_network_sriov_stress.py - [line:614] - root - INFO - Successfully ping sut2
2021-11-26 14:54:30 - test_network_sriov_stress.py - [line:614] - root - INFO - Successfully ping6 sut2
2021-11-26 14:54:30 - test_network_sriov_stress.py - [line:615] - root - INFO - check ---end---
2021-11-26 14:54:35 - sshInstance.py - [line:89] - root - INFO - exit
logout
Connection to 192.168.122.51 closed.
[root@WW30CYP10 ~]# 
.2021-11-26 14:54:38 - test_network_sriov_stress.py - [line:52] - root - INFO - this is the teardown of Test_Network_SRIOV_Stress.
2021-11-26 14:54:41 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2021-11-26 14:54:43 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2021-11-26 14:54:48 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully shut down the VM: VMtest2
2021-11-26 14:54:51 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2021-11-26 14:54:51 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2021-11-26 14:54:56 - test_network_sriov_stress.py - [line:254] - root - INFO - Successfully removed the VM: VMtest2
2021-11-26 14:54:59 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2021-11-26 14:55:00 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2021-11-26 14:55:05 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully shut down the VM: VMtest1
2021-11-26 14:55:08 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2021-11-26 14:55:08 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2021-11-26 14:55:13 - test_network_sriov_stress.py - [line:254] - root - INFO - Successfully removed the VM: VMtest1
2021-11-26 14:55:13 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2021-11-26 14:55:13 - test_network_sriov_stress.py - [line:57] - root - INFO - =============================================Finished run the test case===============================================

../test-nic/npxtester/Tests/testNics/test_nics.py 2021-11-26 14:55:13 - NicTestFixture.py - [line:28] - root - INFO - Starting to run test_silver_Networking_ConnectivityEnableDisable
2021-11-26 14:55:13 - NicTestFixture.py - [line:29] - root - INFO - setup log for testing in the fixture class fbefore
2021-11-26 14:55:13 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2021-11-26 14:55:13 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2021-11-26 14:55:13 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (publickey) failed.
2021-11-26 14:55:13 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2021-11-26 14:55:13 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.157
2021-11-26 14:55:13 - test_nics.py - [line:34] - root - INFO - run silver_Networking_ConnectivityEnableDisable
2021-11-26 14:55:17 - sshInstance.py - [line:69] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Fri Nov 26 14:44:57 2021 from 10.239.129.147
[root@WW30CYP10 ~]# ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.037 ms
2021-11-26 14:55:18 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.019 ms
2021-11-26 14:55:19 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.009 ms
2021-11-26 14:55:20 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.007 ms
2021-11-26 14:55:21 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.007 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4125ms
rtt min/avg/max/mdev = 0.007/0.015/0.037/0.012 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:55:29 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 down
[root@WW30CYP10 ~]# 
2021-11-26 14:55:37 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 up
[root@WW30CYP10 ~]# 
2021-11-26 14:55:44 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.036 ms
2021-11-26 14:55:45 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.012 ms
2021-11-26 14:55:46 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.008 ms
2021-11-26 14:55:47 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.007 ms
2021-11-26 14:55:48 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.007 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4102ms
rtt min/avg/max/mdev = 0.007/0.014/0.036/0.011 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:55:56 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 down
[root@WW30CYP10 ~]# 
2021-11-26 14:56:04 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 up
[root@WW30CYP10 ~]# 
2021-11-26 14:56:11 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.042 ms
2021-11-26 14:56:12 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.011 ms
2021-11-26 14:56:13 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.008 ms
2021-11-26 14:56:14 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.008 ms
2021-11-26 14:56:15 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.011 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4082ms
rtt min/avg/max/mdev = 0.008/0.016/0.042/0.013 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:56:23 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 down
[root@WW30CYP10 ~]# 
2021-11-26 14:56:31 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 up
[root@WW30CYP10 ~]# 
2021-11-26 14:56:38 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.034 ms
2021-11-26 14:56:39 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.011 ms
2021-11-26 14:56:40 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.010 ms
2021-11-26 14:56:41 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.010 ms
2021-11-26 14:56:42 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.016 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4125ms
rtt min/avg/max/mdev = 0.010/0.016/0.034/0.009 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:56:50 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 down
[root@WW30CYP10 ~]# 
2021-11-26 14:56:58 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 up
[root@WW30CYP10 ~]# 
2021-11-26 14:57:05 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.030 ms
2021-11-26 14:57:06 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.010 ms
2021-11-26 14:57:07 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.008 ms
2021-11-26 14:57:08 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.008 ms
2021-11-26 14:57:09 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.009 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4103ms
rtt min/avg/max/mdev = 0.008/0.013/0.030/0.008 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:57:17 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 down
[root@WW30CYP10 ~]# 
2021-11-26 14:57:25 - sshInstance.py - [line:89] - root - INFO - ifconfig ens787f0 up
[root@WW30CYP10 ~]# 
2021-11-26 14:57:32 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.030 ms
2021-11-26 14:57:33 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.012 ms
2021-11-26 14:57:34 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.011 ms
2021-11-26 14:57:35 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.021 ms
2021-11-26 14:57:36 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.008 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4080ms
rtt min/avg/max/mdev = 0.008/0.016/0.030/0.008 ms
[root@WW30CYP10 ~]# 
.2021-11-26 14:57:39 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2021-11-26 14:57:39 - test_nics.py - [line:28] - root - INFO - this is Test_Nics teardown
2021-11-26 14:57:39 - NicTestFixture.py - [line:28] - root - INFO - Starting to run test_silver_ConnectivityReboot
2021-11-26 14:57:39 - NicTestFixture.py - [line:29] - root - INFO - setup log for testing in the fixture class fbefore
2021-11-26 14:57:39 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2021-11-26 14:57:39 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2021-11-26 14:57:39 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (publickey) failed.
2021-11-26 14:57:39 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2021-11-26 14:57:39 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.157
2021-11-26 14:57:39 - test_nics.py - [line:56] - root - INFO - run silver_ConnectivityReboot
2021-11-26 14:57:39 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2021-11-26 14:57:39 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (publickey) failed.
2021-11-26 14:57:39 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2021-11-26 14:57:39 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.157
2021-11-26 14:57:43 - sshInstance.py - [line:69] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Fri Nov 26 14:57:48 2021 from 10.239.129.147
[root@WW30CYP10 ~]# ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.042 ms
2021-11-26 14:57:44 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.021 ms
2021-11-26 14:57:45 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.011 ms
2021-11-26 14:57:46 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.009 ms
2021-11-26 14:57:47 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.008 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4115ms
rtt min/avg/max/mdev = 0.008/0.018/0.042/0.013 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:57:54 - sshInstance.py - [line:69] - root - INFO - ping6 -c 5 -I ens787f0 fe80::b696:91ff:fe9c:f762
ping6: Warning: source address might be selected on device other than ens787f0.
PING fe80::b696:91ff:fe9c:f762(fe80::b696:91ff:fe9c:f762) from :: ens787f0: 56 data bytes
64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=1 ttl=64 time=0.211 ms
2021-11-26 14:57:55 - sshInstance.py - [line:69] - root - INFO - 64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=2 ttl=64 time=0.071 ms
2021-11-26 14:57:56 - sshInstance.py - [line:69] - root - INFO - 64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=3 ttl=64 time=0.032 ms
2021-11-26 14:57:57 - sshInstance.py - [line:69] - root - INFO - 64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=4 ttl=64 time=0.033 ms
2021-11-26 14:57:58 - sshInstance.py - [line:69] - root - INFO - 64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=5 ttl=64 time=0.027 ms

--- fe80::b696:91ff:fe9c:f762 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4110ms
rtt min/avg/max/mdev = 0.027/0.074/0.211/0.070 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:58:01 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2021-11-26 14:58:02 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (publickey) failed.
2021-11-26 14:58:02 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2021-11-26 14:58:02 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.157
2021-11-26 14:58:06 - sshInstance.py - [line:69] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Fri Nov 26 14:57:48 2021 from 10.239.129.147
[root@WW30CYP10 ~]# ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.043 ms
2021-11-26 14:58:07 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.011 ms
2021-11-26 14:58:08 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.009 ms
2021-11-26 14:58:09 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.008 ms
2021-11-26 14:58:10 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.009 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4127ms
rtt min/avg/max/mdev = 0.008/0.016/0.043/0.013 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:58:17 - sshInstance.py - [line:69] - root - INFO - ping6 -c 5 -I ens787f0 fe80::b696:91ff:fe9c:f762
ping6: Warning: source address might be selected on device other than ens787f0.
PING fe80::b696:91ff:fe9c:f762(fe80::b696:91ff:fe9c:f762) from :: ens787f0: 56 data bytes
64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=1 ttl=64 time=0.104 ms
2021-11-26 14:58:18 - sshInstance.py - [line:69] - root - INFO - 64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=2 ttl=64 time=0.047 ms
2021-11-26 14:58:19 - sshInstance.py - [line:69] - root - INFO - 64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=3 ttl=64 time=0.037 ms
2021-11-26 14:58:20 - sshInstance.py - [line:69] - root - INFO - 64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=4 ttl=64 time=0.026 ms
2021-11-26 14:58:21 - sshInstance.py - [line:69] - root - INFO - 64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=5 ttl=64 time=0.033 ms

--- fe80::b696:91ff:fe9c:f762 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4119ms
rtt min/avg/max/mdev = 0.026/0.049/0.104/0.028 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:58:24 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2021-11-26 14:58:24 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (publickey) failed.
2021-11-26 14:58:24 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2021-11-26 14:58:24 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.157
2021-11-26 14:58:28 - sshInstance.py - [line:69] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Fri Nov 26 14:58:11 2021 from 10.239.129.147
[root@WW30CYP10 ~]# ping -c 5 192.168.10.10
PING 192.168.10.10 (192.168.10.10) 56(84) bytes of data.
64 bytes from 192.168.10.10: icmp_seq=1 ttl=64 time=0.044 ms
2021-11-26 14:58:29 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=2 ttl=64 time=0.012 ms
2021-11-26 14:58:30 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=3 ttl=64 time=0.012 ms
2021-11-26 14:58:31 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=4 ttl=64 time=0.009 ms
2021-11-26 14:58:32 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.10: icmp_seq=5 ttl=64 time=0.008 ms

--- 192.168.10.10 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4075ms
rtt min/avg/max/mdev = 0.008/0.017/0.044/0.013 ms
[root@WW30CYP10 ~]# 
2021-11-26 14:58:39 - sshInstance.py - [line:69] - root - INFO - ping6 -c 5 -I ens787f0 fe80::b696:91ff:fe9c:f762
ping6: Warning: source address might be selected on device other than ens787f0.
PING fe80::b696:91ff:fe9c:f762(fe80::b696:91ff:fe9c:f762) from :: ens787f0: 56 data bytes
64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=1 ttl=64 time=0.077 ms
2021-11-26 14:58:40 - sshInstance.py - [line:69] - root - INFO - 64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=2 ttl=64 time=0.046 ms
2021-11-26 14:58:41 - sshInstance.py - [line:69] - root - INFO - 64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=3 ttl=64 time=0.042 ms
2021-11-26 14:58:42 - sshInstance.py - [line:69] - root - INFO - 64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=4 ttl=64 time=0.027 ms
2021-11-26 14:58:43 - sshInstance.py - [line:69] - root - INFO - 64 bytes from fe80::b696:91ff:fe9c:f762%ens787f0: icmp_seq=5 ttl=64 time=0.033 ms

--- fe80::b696:91ff:fe9c:f762 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4132ms
rtt min/avg/max/mdev = 0.027/0.045/0.077/0.017 ms
[root@WW30CYP10 ~]# 
Aborted by [8mha:////4C8zTO/v0UlG+vQ5Fjm5jTf9kR93yL5yxTMP2X04T9v8AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgYu/dLi1CL9ovz8EgDKVWzSvwAAAA==[0mroot
Sending interrupt signal to process
/root/.jenkins/workspace/test-nic@2@tmp/durable-9d4c2283/script.sh: line 1: 961561 Terminated              python /root/.jenkins/workspace/test-nic/npxtester/Tests/testNics/nic_main.py
script returned exit code 143
[8mha:////4KMKnj+jwomtBZRlOM1zDNsT7NVP2UylJUBAmwQdpqOFAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyGUvHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzN4nqNv9p9o3geV5574AAAA=[0m[Pipeline] }
[8mha:////4PHbOgS4fTQzlO31aLQygq6Gmyy7LbpReNAbbgHuNOsPAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICEh2iSmu54QUmNsaJdWdsh6TiRXyNPxCIRMUWq51t5vmCZYpw5GixNdQ5So3D4Hs7LRw4dhfPA7Z8xoYpsTcozSBZm3pGydnAnKKEhYCVocZzcmQzrEWr7qryimx1ynH6DgJKp2/wgEJM5qxi/sIYYXPtdWL6ef4KYAwhQ7nbf2r7Bq/le42+AAAA[0m[Pipeline] // stage
[8mha:////4I9CBL1TQQZuqbZ2jRHSmcHnuMbbRTwUd9k6KAOagwtcAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRElSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsXZLsP9aSlGr0AAAA=[0m[Pipeline] }
[8mha:////4AgCtwjc4t5tcZsCa10f3l1mNPWqCUOes7yjbzZP2H6lAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRQqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5Nu9INt9AIZLYcO9AAAA[0m[Pipeline] // node
[8mha:////4HNhgbRMdr5fLy6tNmZPXDu18JtR1J6yjnVzc/IrJ0XIAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRNBSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsXZLsPoFIGib0AAAA=[0m[Pipeline] End of Pipeline
Finished: ABORTED
